import { ASSET_BASE } from './theme';

export const ASSETS = {
  brand: {
    logo: `${ASSET_BASE}/img_00_brand/brand_logo.png`,
    mainVisual: `${ASSET_BASE}/img_00_brand/brand_main_visual.png`,
    sharePoster: `${ASSET_BASE}/img_00_brand/brand_share_poster.png`,
  },
  npc: {
    hulaofuzi: `${ASSET_BASE}/img_01_npc/npc_0_hulaofuzi.png`,
    huwenguang: `${ASSET_BASE}/img_01_npc/npc_1_huwenguang.png`,
    huwenzhao: `${ASSET_BASE}/img_01_npc/npc_4_huwenzhao.png`,
    hushangyan: `${ASSET_BASE}/img_01_npc/npc_5_hushangyan.png`,
    xiulousister: `${ASSET_BASE}/img_01_npc/npc_4_xiulou_sister.png`,
    huguansan: `${ASSET_BASE}/img_01_npc/npc_5_huguansan.png`,
  },
  scene: {
    entrance: `${ASSET_BASE}/img_02_scene/scene_entrance.png`,
    paifang: `${ASSET_BASE}/img_02_scene/scene_paifang.png`,
    ruiyuting: `${ASSET_BASE}/img_02_scene/scene_ruiyuting.png`,
    jingaitang: `${ASSET_BASE}/img_02_scene/scene_jingaitang.png`,
    dafudi: `${ASSET_BASE}/img_02_scene/scene_dafudi.png`,
    lvfutang: `${ASSET_BASE}/img_02_scene/scene_lvfutang.png`,
    finale: `${ASSET_BASE}/img_02_scene/scene_finale.png`,
    foodStall: `${ASSET_BASE}/img_02_scene/scene_food_stall.png`,
    teahouse: `${ASSET_BASE}/img_02_scene/scene_teahouse.png`,
  },
  ui: {
    checkpointFrame: `${ASSET_BASE}/img_03_ui/ui_checkpoint_frame.png`,
    checkpointFrameAlt: `${ASSET_BASE}/img_03_ui/ui_checkpoint_frame_alt.png`,
    jingtianLetter: `${ASSET_BASE}/img_03_ui/ui_jintian_letter.png`,
    mapIcons: `${ASSET_BASE}/img_03_ui/ui_map_icons.png`,
    mibaoBanner: `${ASSET_BASE}/img_03_ui/ui_mibao_banner.png`,
    sealFrame: `${ASSET_BASE}/img_03_ui/ui_seal_frame.png`,
    sharePoster: `${ASSET_BASE}/img_03_ui/ui_share_poster.png`,
    sharePosterBg: `${ASSET_BASE}/img_03_ui/ui_share_poster_bg.png`,
  },
  item: {
    compass: `${ASSET_BASE}/img_04_item/item_0_compass.png`,
    genealogy: `${ASSET_BASE}/img_04_item/item_0_genealogy.png`,
    magnifier: `${ASSET_BASE}/img_04_item/item_0_magnifier.png`,
    stampZhong: `${ASSET_BASE}/img_04_item/item_1_stamp_zhong.png`,
    stampQin: `${ASSET_BASE}/img_04_item/item_2_stamp_qin.png`,
    stampHe: `${ASSET_BASE}/img_04_item/item_3_stamp_he.png`,
    stampXiao: `${ASSET_BASE}/img_04_item/item_4_stamp_xiao.png`,
    stampDu: `${ASSET_BASE}/img_04_item/item_5_stamp_du.png`,
  },
  quiz: {
    paifangMarker: `${ASSET_BASE}/img_05_quiz/quiz_1_paifang_marker.png`,
    paifangOverview: `${ASSET_BASE}/img_05_quiz/quiz_1_paifang_overview.png`,
    angleA: `${ASSET_BASE}/img_05_quiz/quiz_2_angle_a.jpg`,
    angleB: `${ASSET_BASE}/img_05_quiz/quiz_2_angle_b.jpg`,
    angleC: `${ASSET_BASE}/img_05_quiz/quiz_2_angle_c.jpg`,
    cuoziCouplet: `${ASSET_BASE}/img_05_quiz/quiz_2_cuozi_couplet.jpg`,
    ancestorMing: `${ASSET_BASE}/img_05_quiz/quiz_3_ancestor_ming.png`,
    ancestorQing: `${ASSET_BASE}/img_05_quiz/quiz_3_ancestor_qing.png`,
    ancestorTang: `${ASSET_BASE}/img_05_quiz/quiz_3_ancestor_tang.png`,
    xiaoziLeft: `${ASSET_BASE}/img_05_quiz/quiz_3_xiaozi_left.png`,
    xiaoziRight: `${ASSET_BASE}/img_05_quiz/quiz_3_xiaozi_right.png`,
  },
  food: {
    huangshanCake: `${ASSET_BASE}/img_06_food/food_1_huanshan_cake.jpg`,
    huangshanCakeScene: `${ASSET_BASE}/img_06_food/food_1_huanshan_cake_scene.jpg`,
    maofengTea: `${ASSET_BASE}/img_06_food/food_2_maofeng_tea.jpg`,
    maofengTeaScene: `${ASSET_BASE}/img_06_food/food_2_maofeng_tea_scene.jpg`,
  },
  special: {
    xiangrikui: `${ASSET_BASE}/img_07_special/special_4_xiangrikui.png`,
    xiulouScene: `${ASSET_BASE}/img_07_special/special_4_xiulou_scene.png`,
    xiayiTomb: `${ASSET_BASE}/img_07_special/special_6_xiayi_tomb.png`,
    matouqiang: `${ASSET_BASE}/img_07_special/special_caidan_matouqiang.png`,
  },
  fx: {
    ballThrow: `${ASSET_BASE}/img_08_fx/fx_ball_throw.png`,
    scrollOpen: `${ASSET_BASE}/img_08_fx/fx_scroll_open.png`,
    sealAppear: `${ASSET_BASE}/img_08_fx/fx_seal_appear.png`,
  },
  audio: {
    ballCatch: `${ASSET_BASE}/audio/sfx_ball_catch.mp3`,
    cameraShutter: `${ASSET_BASE}/audio/sfx_camera_shutter.mp3`,
    click: `${ASSET_BASE}/audio/sfx_click.mp3`,
    error: `${ASSET_BASE}/audio/sfx_error.mp3`,
    itemGet: `${ASSET_BASE}/audio/sfx_item_get.mp3`,
    letterOpen: `${ASSET_BASE}/audio/sfx_letter_open.mp3`,
    pageTurn: `${ASSET_BASE}/audio/sfx_page_turn.mp3`,
    sealAppear: `${ASSET_BASE}/audio/sfx_seal_appear.mp3`,
    success: `${ASSET_BASE}/audio/sfx_success.mp3`,
    unlock: `${ASSET_BASE}/audio/sfx_unlock.mp3`,
    voiceHulaofuzi: `${ASSET_BASE}/audio/voice_hulaofuzi.mp3`,
    voiceHushangyan: `${ASSET_BASE}/audio/voice_hushangyan.mp3`,
    voiceHuwenguang: `${ASSET_BASE}/audio/voice_huwenguang.mp3`,
    voiceHuwenzhao: `${ASSET_BASE}/audio/voice_huwenzhao.mp3`,
  },
} as const;
