import type { ChapterConfig, Landmark, Item, EncyclopediaEntry } from '../types/game';
import { ASSETS } from './assets';

export const CHAPTERS: ChapterConfig[] = [
  {
    id: 'chapter1_paifang',
    title: '牌坊之启',
    subtitle: '胡文光牌楼',
    npcId: 'huwenguang',
    landmarkId: 'landmark_paifang',
    stampId: 'stamp_zhong',
    stampName: '忠',
    bgImagePath: ASSETS.scene.paifang,
    npcImagePath: ASSETS.npc.huwenguang,
  },
  {
    id: 'chapter2_ruiyuting',
    title: '商字之谜',
    subtitle: '瑞玉庭',
    npcId: 'hulaofuzi',
    landmarkId: 'landmark_ruiyuting',
    stampId: 'stamp_qin',
    stampName: '勤',
    bgImagePath: ASSETS.scene.ruiyuting,
    npcImagePath: ASSETS.npc.hulaofuzi,
  },
  {
    id: 'chapter3_jingaitang',
    title: '百善之门',
    subtitle: '敬爱堂',
    npcId: 'hulaofuzi',
    landmarkId: 'landmark_jingaitang',
    stampId: 'stamp_xiao',
    stampName: '孝',
    bgImagePath: ASSETS.scene.jingaitang,
    npcImagePath: ASSETS.npc.hulaofuzi,
  },
  {
    id: 'chapter4_dafudi',
    title: '退让之德',
    subtitle: '大夫第',
    npcId: 'huwenzhao',
    landmarkId: 'landmark_dafudi',
    stampId: 'stamp_he',
    stampName: '和',
    bgImagePath: ASSETS.scene.dafudi,
    npcImagePath: ASSETS.npc.huwenzhao,
  },
  {
    id: 'chapter5_lvfutang',
    title: '读书之道',
    subtitle: '履福堂',
    npcId: 'hushangyan',
    landmarkId: 'landmark_lvfutang',
    stampId: 'stamp_du',
    stampName: '读',
    bgImagePath: ASSETS.scene.lvfutang,
    npcImagePath: ASSETS.npc.hushangyan,
  },
];

// 根据导览图核对手绘地图坐标（map.png 2388×1544）
export const LANDMARKS: Landmark[] = [
  {
    id: 'landmark_paifang',
    name: '胡文光牌楼',
    chapterId: 'chapter1_paifang',
    x: 22,
    y: 86,
    iconPath: ASSETS.ui.mapIcons,
    locked: false,
    completed: false,
  },
  {
    id: 'landmark_ruiyuting',
    name: '瑞玉庭',
    chapterId: 'chapter2_ruiyuting',
    x: 36,
    y: 60,
    iconPath: ASSETS.ui.mapIcons,
    locked: true,
    completed: false,
  },
  {
    id: 'landmark_jingaitang',
    name: '敬爱堂',
    chapterId: 'chapter3_jingaitang',
    x: 54,
    y: 44,
    iconPath: ASSETS.ui.mapIcons,
    locked: true,
    completed: false,
  },
  {
    id: 'landmark_dafudi',
    name: '大夫第',
    chapterId: 'chapter4_dafudi',
    x: 60,
    y: 32,
    iconPath: ASSETS.ui.mapIcons,
    locked: true,
    completed: false,
  },
  {
    id: 'landmark_lvfutang',
    name: '履福堂',
    chapterId: 'chapter5_lvfutang',
    x: 66,
    y: 20,
    iconPath: ASSETS.ui.mapIcons,
    locked: true,
    completed: false,
  },
];

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'item_genealogy',
    name: '族谱残页',
    description: '遇到祠堂、牌位时自动高亮关键信息',
    iconPath: ASSETS.item.genealogy,
    acquired: false,
    category: 'tool',
  },
  {
    id: 'item_magnifier',
    name: '放大镜',
    description: '观察三雕细节时自动圈出可疑区域',
    iconPath: ASSETS.item.magnifier,
    acquired: false,
    category: 'tool',
  },
  {
    id: 'item_compass',
    name: '简易罗盘',
    description: '在建筑格局分析时显示大致方向提示',
    iconPath: ASSETS.item.compass,
    acquired: false,
    category: 'tool',
  },
  {
    id: 'stamp_zhong',
    name: '忠字印',
    description: '第一幕·胡文光牌楼',
    iconPath: ASSETS.item.stampZhong,
    acquired: false,
    category: 'stamp',
  },
  {
    id: 'stamp_qin',
    name: '勤字印',
    description: '第二幕·瑞玉庭',
    iconPath: ASSETS.item.stampQin,
    acquired: false,
    category: 'stamp',
  },
  {
    id: 'stamp_xiao',
    name: '孝字印',
    description: '第三幕·敬爱堂',
    iconPath: ASSETS.item.stampXiao,
    acquired: false,
    category: 'stamp',
  },
  {
    id: 'stamp_he',
    name: '和字印',
    description: '第四幕·大夫第',
    iconPath: ASSETS.item.stampHe,
    acquired: false,
    category: 'stamp',
  },
  {
    id: 'stamp_du',
    name: '读字印',
    description: '第五幕·履福堂',
    iconPath: ASSETS.item.stampDu,
    acquired: false,
    category: 'stamp',
  },
];

export const ENCYCLOPEDIA_ENTRIES: EncyclopediaEntry[] = [
  {
    id: 'ency_paifang',
    title: '胡文光牌楼：四柱三间五楼式',
    category: '牌坊与建筑',
    summary: '胡文光牌楼采用典型的"四柱三间五楼"形制，是中国古代功名牌坊中的顶级规格。',
    detail: '四柱代表稳固根基，暗合"四平八稳"之意；三间象征天地人三才之道；五楼则是等级标志——楼越多，主人的官阶和功绩越高。胡文光曾任胶州刺史、荆藩首相，万历皇帝特赐建此牌楼。',
    trivia: '胡文光牌楼是西递村唯一留存至今的古牌坊。数百年来，它经历了无数次风雨，甚至连特殊年代都奇迹般地保存了下来。',
    unlockChapterId: 'chapter1_paifang',
    unlocked: true,
  },
  {
    id: 'ency_animals',
    title: '石雕鹤鹿龙虎狮的象征',
    category: '三雕艺术',
    summary: '牌楼上的鹤、鹿、龙、虎、狮五种动物石雕，分别代表仁、礼、智、义、信五种儒家美德。',
    detail: '鹤为长寿之鸟，象征"仁"；鹿谐音"禄"，象征"礼"；龙能升能隐，象征"智"；虎为百兽之王，象征"义"；狮子守护门庭，象征"信"。',
    trivia: '古代工匠雕刻这些动物时，会在动物的眼睛里嵌入黑色石子，让眼睛看起来炯炯有神。',
    unlockChapterId: 'chapter1_paifang',
    unlocked: true,
  },
  {
    id: 'ency_li_hu',
    title: '「真李假胡」的改姓渊源',
    category: '宗族历史',
    summary: '西递胡氏的始祖胡昌翼，本是唐昭宗李晔的幼子，为避朱温之乱而改姓胡。',
    detail: '唐朝末年，朱温篡权，唐昭宗将幼子托付给近臣胡三公带出宫外。为躲避追杀，孩子改姓胡，取名昌翼。长大后考取明经科，学识渊博。',
    trivia: '西递村的名字其实也与这段历史有关。"西"指向唐朝故都长安的方向，"递"意为传承——西递，就是"向西递传李唐血脉"之意。',
    unlockChapterId: 'chapter1_paifang',
    unlocked: true,
  },
];

export const PROLOGUE_DIALOGUE = [
  {
    speakerId: 'narrator' as const,
    text: '有缘人亲启：吾乃明经胡氏后人，先祖昌翼公留有遗训——「五堂归一，秘档自现」。今吾年事已高，恐此秘密永埋尘土，特寻有缘之人。',
  },
  {
    speakerId: 'hulaofuzi' as const,
    text: '年轻人，你终于来了！我是这村里的胡老夫子。咱们胡家的老祖宗昌翼公，是唐朝皇帝的后代，为了躲战乱改姓胡，在这个村子住了下来。',
  },
  {
    speakerId: 'hulaofuzi' as const,
    text: '他临走前留下一份「明经秘档」，分成五块藏在村里五处地方。你把这五块找齐，我就告诉你秘档里写了什么。',
  },
  {
    speakerId: 'hulaofuzi' as const,
    text: '我会给你三件小工具——族谱残页、放大镜、简易罗盘。遇到难题它们会自动帮你，不用操心。你准备好了吗？',
  },
];
